### ISSUE TITLE
Server highlight server failed to start: Connection is already listening

### ISSUE THREAD

**Issue by nkhlmn** [neoclide/coc-highlight#26]
Started getting this message when opening neovim on macos and highlighting of colors is no longer working. Same result when using kitty or iterm 2:
`[coc.nvim] Server highlight server failed to start: Connection is already listening`

Output of `:CocInfo`:
```
## versions

vim version: NVIM v0.4.3
node version: v13.7.0
coc.nvim version: 0.0.77-daefc02592
term: xterm-kitty
platform: darwin

## Messages
[coc.nvim] Server highlight server failed to start: Connection is already listening
1 line less; before #1  1 second ago
## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /Users/nikhil
fatal: not a git repository (or any of the parent directories): .git

## Output channel: snippets


## Output channel: prettier


## Output channel: highlight

[Error  - 2:43:33 PM] Starting client failed: 
Error: Connection is already listening
    at throwIfListening (/Users/nikhil/.config/nvim/plugged/coc.nvim/build/index.js:16095:19)
    at Object.listen (/Users/nikhil/.config/nvim/plugged/coc.nvim/build/index.js:16334:13)
    at Object.listen (/Users/nikhil/.config/nvim/plugged/coc.nvim/build/index.js:54368:34)
    at /Users/nikhil/.config/nvim/plugged/coc.nvim/build/index.js:56412:24
[Info  - 2:43:33 PM] Highlight server running in node v13.7.0
[Error  - 2:43:33 PM] (node:18608) UnhandledPromiseRejectionWarning: Error: Unhandled method highlight/iskeyword
    at handleResponse (/Users/nikhil/.config/coc/extensions/node_modules/coc-highlight/lib/server.js:614:48)
    at processMessageQueue (/Users/nikhil/.config/coc/extensions/node_modules/coc-highlight/lib/server.js:441:17)
    at Immediate.<anonymous> (/Users/nikhil/.config/coc/extensions/node_modules/coc-highlight/lib/server.js:425:13)
    at processImmediate (internal/timers.js:456:21)
[Error  - 2:43:33 PM] (node:18608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[Error  - 2:43:33 PM] (node:18608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Output of `:CocOpenLog`:
```
2020-03-17T14:47:03.207 INFO (pid:18652) [services] - registered service "eslint langserver"
2020-03-17T14:47:03.218 INFO (pid:18652) [services] - registered service "highlight server"
2020-03-17T14:47:03.365 INFO (pid:18652) [plugin] - coc 0.0.77-daefc02592 initialized with node: v13.7.0
2020-03-17T14:47:03.369 INFO (pid:18652) [language-client-index] - highlight started with 18654
2020-03-17T14:47:03.373 INFO (pid:18652) [services] - highlight server state change: starting => stopped
2020-03-17T14:47:03.394 ERROR (pid:18652) [extension-coc-highlight] - highlight server start failed: Connection is already listening
2020-03-17T14:47:03.427 INFO (pid:18652) [services] - highlight server state change: stopped => running
```

Let me know if I can provide any other info. Thanks!

**Comment by chemzqm** [comment]
Fixed on latest coc.nvim
